### ISSUE TITLE
not able to see demo page on opera browser

### ISSUE THREAD

**Issue by 808vita** [th0th/poeticmetric#194]
browser details: opera v101
not able to see demo page on opera browser but works on chrome latest version.
Did not load even when I tried to directly load by url : https://www.poeticmetric.com/s?d=www.poeticmetric.com&end=2023-08-12T18%3A29%3A59.999Z&start=2023-07-13T18%3A30%3A00.000Z

I have not tested in other browsers.

![image](https://github.com/th0th/poeticmetric/assets/97225946/268efea7-613a-476f-a195-d3a9d8951a63)

**Comment by th0th** [comment]
It is working for me on the Opera's latest version:

<img width="1085" alt="Screenshot 2023-08-12 at 19 56 26" src="https://github.com/th0th/poeticmetric/assets/698079/4ec72f31-52cb-4c6a-8611-ce470c8f4f07">

Are you using any ad blockers? It might be the reason. Can you please open your browser's console, and see if there is anything relevant?

**Comment by 808vita** [comment]
The tracker was blocked by opera's "Block trackers" setting.
After switching it off, the page does load. Logs did show that it was being blocked on the client side.

I had ad blocker on chrome but the page loaded anyway .

**Comment by 808vita** [comment]
![image](https://github.com/th0th/poeticmetric/assets/97225946/4288524a-41d3-4570-878b-808de7ceb8ca)

**Comment by CarlSinclair** [comment]
I can't open the website either, probably because of my pi-hole. 

Any chance of adding the docs into the repo?

**Comment by th0th** [comment]
> I can't open the website either, probably because of my pi-hole.
> 
> Any chance of adding the docs into the repo?

The docs are already in the repo here: https://github.com/th0th/poeticmetric/tree/main/frontend/docs
